/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      screens: {
        compact: '320px',
        phone: '375px',
        canvas: '1440px',
      },
      fontFamily: {
        display: ['var(--db-font-display)'],
        title: ['var(--db-font-display)'],
        heading: ['var(--db-font-sans)'],
        body: ['var(--db-font-sans)'],
        sans: ['var(--db-font-sans)'],
        research: ['var(--db-font-mono)'],
      },
      colors: {
        'brand-midnight': 'rgb(var(--db-color-midnight-horizon-rgb) / <alpha-value>)',
        'brand-twilight': 'rgb(var(--db-color-twilight-violet-rgb) / <alpha-value>)',
        'brand-rose': 'rgb(var(--db-color-horizon-rose-rgb) / <alpha-value>)',
        'brand-coral': 'rgb(var(--db-color-sunrise-coral-rgb) / <alpha-value>)',
        'brand-light': 'rgb(var(--db-color-morning-light-rgb) / <alpha-value>)',
        background: 'rgb(var(--db-background-rgb) / <alpha-value>)',
        'background-subtle': 'rgb(var(--db-background-subtle-rgb) / <alpha-value>)',
        foreground: 'rgb(var(--db-text-primary-rgb) / <alpha-value>)',
        surface: 'rgb(var(--db-surface-rgb) / <alpha-value>)',
        'surface-elevated': 'rgb(var(--db-surface-elevated-rgb) / <alpha-value>)',
        'text-primary': 'rgb(var(--db-text-primary-rgb) / <alpha-value>)',
        'text-secondary': 'rgb(var(--db-text-secondary-rgb) / <alpha-value>)',
        'text-muted': 'rgb(var(--db-text-muted-rgb) / <alpha-value>)',
        card: 'rgb(var(--db-surface-rgb) / <alpha-value>)',
        'card-foreground': 'rgb(var(--db-text-primary-rgb) / <alpha-value>)',
        border: 'rgb(var(--db-border-rgb) / <alpha-value>)',
        'border-strong': 'rgb(var(--db-border-strong-rgb) / <alpha-value>)',
        input: 'rgb(var(--db-border-rgb) / <alpha-value>)',
        primary: 'rgb(var(--db-action-primary-rgb) / <alpha-value>)',
        'primary-hover': 'rgb(var(--db-action-primary-hover-rgb) / <alpha-value>)',
        'primary-foreground': 'rgb(23 42 66 / <alpha-value>)',
        secondary: 'rgb(var(--db-action-secondary-rgb) / <alpha-value>)',
        'secondary-foreground': 'rgb(255 255 255 / <alpha-value>)',
        selected: 'rgb(var(--db-selected-rgb) / <alpha-value>)',
        ring: 'rgb(var(--db-focus-ring-rgb) / <alpha-value>)',
        success: 'rgb(var(--db-success-rgb) / <alpha-value>)',
        warning: 'rgb(var(--db-warning-rgb) / <alpha-value>)',
        error: 'rgb(var(--db-error-rgb) / <alpha-value>)',
        destructive: 'rgb(var(--db-error-rgb) / <alpha-value>)',
        muted: 'rgb(var(--db-background-subtle-rgb) / <alpha-value>)',
        'muted-foreground': 'rgb(var(--db-text-muted-rgb) / <alpha-value>)',
        accent: 'rgb(var(--db-selected-rgb) / <alpha-value>)',
        'accent-foreground': 'rgb(255 255 255 / <alpha-value>)',
        overlay: 'var(--db-color-overlay)',
      },
      spacing: {
        gutter: 'var(--db-page-gutter)',
        section: 'var(--db-section-space)',
        touch: 'var(--db-touch-target)',
      },
      maxWidth: {
        'content-narrow': 'var(--db-content-narrow)',
        content: 'var(--db-content-default)',
        'content-wide': 'var(--db-content-wide)',
        prose: '72ch',
      },
      minHeight: { touch: 'var(--db-touch-target)' },
      minWidth: { touch: 'var(--db-touch-target)' },
      borderRadius: {
        sm: 'var(--db-radius-sm)',
        DEFAULT: 'var(--db-radius-md)',
        md: 'var(--db-radius-md)',
        lg: 'var(--db-radius-lg)',
        xl: 'var(--db-radius-xl)',
        full: 'var(--db-radius-pill)',
      },
      borderWidth: { DEFAULT: 'var(--db-border-width)', strong: 'var(--db-border-width-strong)' },
      boxShadow: {
        sm: 'var(--db-shadow-sm)',
        DEFAULT: 'var(--db-shadow-md)',
        md: 'var(--db-shadow-md)',
        lg: 'var(--db-shadow-lg)',
        focus: '0 0 0 var(--db-focus-width) rgb(var(--db-focus-ring-rgb) / 35%)',
      },
      opacity: { disabled: 'var(--db-disabled-opacity)' },
      transitionDuration: {
        fast: 'var(--db-duration-fast)',
        standard: 'var(--db-duration-standard)',
        slow: 'var(--db-duration-slow)',
      },
      transitionTimingFunction: {
        standard: 'var(--db-ease-standard)',
        emphasized: 'var(--db-ease-emphasized)',
      },
      animation: {
        float: 'float 6s var(--db-ease-standard) infinite',
        shimmer: 'shimmer 1.8s linear infinite',
        'mesh-shift': 'meshShift 14s var(--db-ease-standard) infinite alternate',
        'count-up': 'countUp var(--db-duration-slow) var(--db-ease-standard) forwards',
        'fade-up': 'fadeUp var(--db-duration-slow) var(--db-ease-standard) forwards',
        'pulse-soft': 'pulseSoft 2s var(--db-ease-standard) infinite',
      },
      keyframes: {
        float: {
          '0%, 100%': { transform: 'translateY(0)' },
          '50%': { transform: 'translateY(-0.75rem)' },
        },
        shimmer: {
          '0%': { backgroundPosition: '200% 0' },
          '100%': { backgroundPosition: '-200% 0' },
        },
        meshShift: {
          '0%': { backgroundPosition: '0% 50%' },
          '100%': { backgroundPosition: '100% 50%' },
        },
        countUp: {
          from: { opacity: '0', transform: 'translateY(0.5rem)' },
          to: { opacity: '1', transform: 'translateY(0)' },
        },
        fadeUp: {
          from: { opacity: '0', transform: 'translateY(1rem)' },
          to: { opacity: '1', transform: 'translateY(0)' },
        },
        pulseSoft: {
          '0%, 100%': { opacity: '0.55' },
          '50%': { opacity: '1' },
        },
      },
    },
  },
  plugins: [],
}
